server:
  port: 10002
  tomcat:
    max-threads: 1

spring:
  application:
    name: mcook-soa
  redisson:
    address: redis://120.26.142.247:6379
  datasource:
    url: jdbc:mysql://192.168.32.225:3306/dev_smartcook?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hxr
    type: com.alibaba.druid.pool.DruidDataSource
  elasticsearch:
    rest:
      uris: http://localhost:9200
#es:
#  host: 127.0.0.1
#  port: 9200
#  scheme: http


anti:
  reptile:
    manager:
      enabled: true
      include-urls: ^/admin/.*$
#      globalFilterMode: true
      ip-rule:
        request-max-size: 1


# mybatis-plus 相关配置
mybatis-plus:
  # MyBatis 别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.iotmars.po
  # MyBatis Mapper 所对应的 XML 文件位置，如果您在 Mapper 中有自定义方法
  mapper-locations: classpath:/mapper/*Mapper.xml


logging:
  level:
    com.iotmars: debug